account_id: 614cfdc4c1a8b0e4e76af70d
agent_system_id: c73945a7-e742-4746-93fa-d3e7845d8732
system_version: 14
status: DRAFT
agent_system_name: FSI Providers Multi Agent - hehua
agent_system_description: ''
guardrail: ''
conversation_settings:
  enabled: false
  is_dynamic_filler: false
  initial_delay: 1
  filler_interval: 2
  number_of_retries: 1
  initial_messages: []
  retry_messages: []
  channels:
  - channel_type: default
    languages:
    - language_code: default
      initial_delay: 1
      filler_interval: 2
      number_of_retries: 1
      initial_messages: []
      retry_messages: []
markers: []
application_output_settings:
  type: value
  value: ''
inactivity_user_settings:
  is_active: false
  channel_setting_map: {}
custom_guardrail_settings:
  is_active: false
  channel_custom_guardrail_settings: {}
welcome_message_settings:
  is_active: false
  channel_setting_map:
    default:
      language_message_map:
        default: ''
language_lock_settings:
  is_active: false
  channel_setting_map:
    voice_voice:
      turns_until_lang_lock: 1
      language_selection_mechanism: MAJORITY
    voice_simulator:
      turns_until_lang_lock: 1
      language_selection_mechanism: MAJORITY
